apiVersion: v2
name: secure-ingress
description: A Helm chart for deploying secure ingress with cert-manager
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ingress
  - cert-manager
  - nginx
maintainers:
  - name: DevOps Team

dependencies:
  - name: cert-manager
    version: "v1.12.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
