apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nadavcool543/secure-ingress-chart.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-cert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
