apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/aws-secretANDsecure-ingress.git  # Replace with your actual repository URL
    targetRevision: HEAD
    path: secure-ingress-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-cert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
