namespace: custom-namespace

serviceAccount:
  create: true
  annotations: {}
  name: "secure-ingress-sa"

service:
  name: custom-nginx-service
  port: 8080
  targetPort: 8080
  selector:
    app: nginx

ingress:
  name: custom-nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  host: custom.example.com
  tls:
    secretName: custom-tls
  backend:
    serviceName: custom-nginx-service
    servicePort: 8080

cert-manager:
  enabled: true
  installCRDs: false  

  global:
    leaderElection:
      namespace: cert-manager

  prometheus:
    enabled: true
    servicemonitor:
      enabled: false

  webhook:
    enabled: true

  cainjector:
    enabled: true

clusterIssuer:
  name: selfsigned-issuer
  create: true
